# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"random_genome": "random_genome_to_midi.ipynb",
         "Note": "random_genome_to_midi.ipynb",
         "events_length": "random_genome_to_midi.ipynb",
         "NoteOn": "random_genome_to_midi.ipynb",
         "NoteOff": "random_genome_to_midi.ipynb",
         "events_on_off": "random_genome_to_midi.ipynb",
         "genome2midi": "random_genome_to_midi.ipynb"}

modules = ["random_genome_to_midi.py"]

doc_url = "https://leoauri.github.io/genetic_musical_generator/"

git_url = "https://github.com/leoauri/genetic_musical_generator/tree/master/"

def custom_doc_links(name): return None
