# AUTOGENERATED! DO NOT EDIT! File to edit: breed.ipynb (unless otherwise specified).

__all__ = ['crossover', 'mutate', 'mutate_crossover']

# Cell
from random import random, choices

# Cell
def crossover(a, b, swap_prob = 0.3, throw_prob = 0.3):
    a = iter(a)
    b = iter(b)
    ptr = a

    child = ''

    try:
        while True:
            if random()<swap_prob:
                ptr = b if ptr is a else a
                while random()<throw_prob:
                    next(ptr)
            child += next(ptr)

    except StopIteration:
        return child

# Cell
def mutate(genome, skip_prob=0.01, change_prob=0.02, add_prob=0.01, alphabet='UDFBS'):
    copy_prob = 1-skip_prob-change_prob-add_prob
    output = ''
    for g in genome:
        transformation = choices([
            lambda l: l,
            lambda l: '',
            lambda l: choices(alphabet)[0],
            lambda l: l+choices(alphabet)[0]
        ], weights=[copy_prob,skip_prob,change_prob,add_prob])[0]
        output += transformation(g)
    return output

# Cell
mutate_crossover = lambda a,b: mutate(crossover(a,b))