# AUTOGENERATED! DO NOT EDIT! File to edit: evolution.ipynb (unless otherwise specified).

__all__ = ['outport', 'hear']

# Cell
from .random_genome_to_midi import genome2midi
import mido

outport = mido.open_output('mido_out', virtual=True)

# Cell
def hear(genome):
    print(genome)
    song = genome2midi(genome)
    for m in song.play():
        outport.send(m)